#eureka:
#  instance:
#    appname: statement
#    hostname: localhost
#
#server:
#  port: 7010
#
#spring:
#  kafka:
#    bootstrap-servers: kafka.lab.viridian.cc:9092
#
#topic:
#  statement:
#    jobs: feronti-jobs1
#    update: feronti-updates1
#
#
#database:
#  jdbc-driver: org.postgresql.Driver
#  url: jdbc:postgresql://postgres.lab.viridian.cc:5432/viridian
#  user: viridian
#  password: sesamo
