eureka:
  instance:
    appname: statement
    hostname: localhost

server:
  port: 7010

spring:
  kafka:
    bootstrap-servers: 142.93.60.121:9092

topic:
  statement:
    jobs: jobs1


database:
  jdbc-driver: org.postgresql.Driver
  url2: jdbc:postgresql://localhost:5432/statement
  url: jdbc:postgresql://142.93.60.121:5432/statement
  user: postgres
  password: sample